### ISSUE TITLE
Ownership of the package

### ISSUE THREAD

**Issue by i6mi6** [i6mi6/react-native-alphabetlistview#41]
This is an awesome package and I'd like to see it updated. If the owner wishes to pass on the ownership to me it'd be great. Thanks for the awesome package!

**Comment by sunnylqm** [comment]
Thanks for your volunteering! To your personal account or your org account? You need to delete your fork first if to your personal account.

**Comment by sunnylqm** [comment]
And also your npm account.

**Comment by i6mi6** [comment]
My personal account. Npm user: i6mi6
