### ISSUE TITLE
Not working with React version 15.5 and above

### ISSUE THREAD

**Issue by komodor8** [i6mi6/react-native-alphabetlistview#49]
This package is not working for React version 15.5 and above because of Typechecking With PropTypes and SectionList class.

we have to import the PropTypes package

>  import PropTypes from prop-types;

**Comment by akinolu52** [comment]
@komodor8 @sunnylqm @sibelius @i6mi6 @ianhowe76 any fix

**Comment by skurgansky-sugarcrm** [comment]
it's fixed on master as far as i can see. it's an issue for published version on **npm**

**Comment by i6mi6** [comment]
Just updated the the npm package.
